apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
 labels:
   app: ratelimit-demo
 name: filter-ratelimit-actions
 namespace: backend
spec:
 configPatches:
   - applyTo: VIRTUAL_HOST
     match:
       context: SIDECAR_INBOUND
       routeConfiguration:
         vhost:
           name: "inbound|http|8899" # port must be a port your Service is listening on
           domains:
            - "*"
           route:
            action: ANY
     patch:
       operation: MERGE
       value:
          rate_limits:
            - actions: # any actions in here
              - request_headers:
                  header_name: "x-user-domain"
                  descriptor_key: "service"
 workloadSelector:
    component: backend
    project: demo