apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
 labels:
   app: ratelimit-demo
 name: filter-ratelimit
 namespace: backend
spec:
 configPatches:
   - applyTo: HTTP_FILTER
     match:
       context: SIDECAR_INBOUND
       listener:
         filterChain:
           filter:
             name: envoy.http_connection_manager
             subFilter:
               name: envoy.router
     patch:
       operation: INSERT_BEFORE
       value:
         config:
           domain: bloomreach # must match domain in ratelimit ConfigMap
           failure_mode_deny: false # run plugin in fail-open mode, no limiting happens if ratelimit is unavailable
           rate_limit_service:
             grpc_service:
               envoy_grpc:
                 cluster_name: rate_limit_service
               timeout: 3.25s
         name: envoy.rate_limit
   - applyTo: CLUSTER
     match:
       cluster:
         service: ratelimit-server-service.ratelimit.svc.cluster.local
     patch:
       operation: ADD
       value:
         connect_timeout: 3.25s
         hosts:
           - socket_address:
               address: ratelimit-server-service.ratelimit.svc.cluster.local # ratelimit Service name
               port_value: 42081 # and port exposed by the Service
         http2_protocol_options: {}
         lb_policy: ROUND_ROBIN
         name: rate_limit_service
         type: STRICT_DNS
 workloadSelector:
    component: backend
    project: demo