---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-v2
  namespace: backend
  labels:
    component: backend
    project: demo
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
      project: demo
      version: v2
  template:
    metadata:
      labels:
        component: backend
        project: demo
        version: v2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

