---
apiVersion: v1
kind: Service
metadata:
  name: ratelimit-redis-service
  namespace: ratelimit
  labels:
    app: ratelimit-server
    component: redis
    project: demo
    kind: service
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: ratelimit-server
    component: redis
    project: demo
    kind: pod
