apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-cm
  namespace: ratelimit
data:
  config.yaml: |
    domain: productpage-ratelimit
    descriptors:
      - key: service
        rate_limit:
          unit: minute
          requests_per_unit: 4
